---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-demo
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: spring-boot-demo
    repoURL: git@github.com:marknazareno/gitops-apps-prod.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}